apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: wechat-article-editor
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx # 根据你的 ingress controller 修改
  rules:
    - host: md.editor.72602.online
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: wechat-article-editor
                port:
                  number: 80
  tls:
    - hosts:
        - md.editor.72602.online
      secretName: wechat-article-editor-tls
